apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-crud
  namespace: dev
spec:
  selector:
    matchLabels:
      app: grpc-crud
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-crud
    spec:
      containers:
        - name: grpc-crud
          image: edmartt/grpc-crud:v1.0
          ports:
            - containerPort: 8080
