apiVersion: v1
kind: Service
metadata:
  name: grpc-crud-service
  namespace: dev
spec:
  selector:
    app: grpc-crud
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30500
  type: NodePort
